version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-nastena
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - nastena_network

  backend:
    build: .
    container_name: backend-nastena
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-nastena:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - nastena_network

volumes:
  postgres_data:
    driver: local

networks:
  nastena_network:
    driver: bridge